// Generated by https://quicktype.io

export interface Book {
  id: number;
  author: string;
  title: string;
  genre: string;
  publisher: string;
  year: string;
  image_url: string;
  description: null;
}
